syntax = "proto3";

package user;

option go_package = "./user";

message UserEntity{
  string id = 1;
  string avatar = 2;
  string nickname = 3;
  string phone = 4;
  int32 status = 5;
  int32 sex = 6;
}

message Request{
  string ping = 1;
}

message Response{
  string pong = 1;
}

message LoginReq{
  string phone = 1;
  string password = 2;
}

message LoginResp{
  string Token = 1;
  int64 expire = 2;
}

message RegisterReq{
  string phone = 1;
  string nickname = 2;
  string password = 3;
  string avatar = 4;
  int32 sex = 5;
}

message RegisterResp {
  string Token = 1;
  int64 expire = 2;
}

message GetUserInfoReq {
  string id = 1;
}

message GetUserInfoResp {
  UserEntity user = 1;
}

message FindUserReq {
  string name = 1;
  string phone = 2;
  repeated string ids = 3;
}

message FindUserResp {
  repeated UserEntity user = 1;
}



service User{
    // 定义用户服务
    rpc Ping(Request) returns (Response);
    // 登录
    rpc Login(LoginReq) returns (LoginResp);
    // 注册
    rpc Register(RegisterReq) returns (RegisterResp);
    // 获取用户信息
    rpc GetUserInfo(GetUserInfoReq) returns (GetUserInfoResp);
    // 查找用户
    rpc FindUser(FindUserReq) returns (FindUserResp);
}